import { NAV_ROUTES, SUB_NAV_ROUTES } from './routes';

const NAV_ROUTE_REGISTER = [
  SUB_NAV_ROUTES.NO_ACCESS,
  SUB_NAV_ROUTES.PROFILE_SETTING,
  NAV_ROUTES.OVERALL_PAGE,
  NAV_ROUTES.CREDIT_PAGE,
  NAV_ROUTES.EDITABLE_PAGE,
  NAV_ROUTES.ACCOUNT_PAGE,
];

const NAV_MENU = [
  NAV_ROUTES.OVERALL_PAGE,
  NAV_ROUTES.CREDIT_PAGE,
  NAV_ROUTES.EDITABLE_PAGE,
  NAV_ROUTES.ACCOUNT_PAGE,
];


export {
  NAV_MENU,
  NAV_ROUTE_REGISTER,
};
