import { NAV_ROUTES, SUB_NAV_ROUTES } from './routes';

const NAV_ROUTE_REGISTER = [
  SUB_NAV_ROUTES.NO_ACCESS,
  SUB_NAV_ROUTES.PROFILE_SETTING,
  SUB_NAV_ROUTES.RESERVATION_REFUND_PAGE,
  NAV_ROUTES.ACCOUNT_PAGE,
  NAV_ROUTES.STORE_GROUP,
  NAV_ROUTES.RESERVATION_GROUP,
  NAV_ROUTES.DOOR_GROUP,
  NAV_ROUTES.BUILDING_GROUP,
  NAV_ROUTES.EVENT_GROUP,
];

const NAV_MENU = [
  NAV_ROUTES.ACCOUNT_PAGE,
  NAV_ROUTES.DOOR_GROUP,
  NAV_ROUTES.STORE_GROUP,
  NAV_ROUTES.RESERVATION_GROUP,
  NAV_ROUTES.BUILDING_GROUP,
  NAV_ROUTES.EVENT_GROUP,
];

export {
  NAV_MENU,
  NAV_ROUTE_REGISTER,
};
